### ISSUE TITLE
Not working on paperspigot 1.12.2

### ISSUE THREAD

**Issue by TheMonDon** [hexosse/AddLight#30]
[23:14:43 ERROR]: Could not pass event PlayerInteractEvent to AddLight v4.3.2
java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
        at com.github.hexocraft.addlight.integrations.WorldEditHooker.isLocationInSelection(WorldEditHooker.java:99) ~[?:?]
        at com.github.hexocraft.addlight.LightsApi.createLight(LightsApi.java:139) ~[?:?]
        at com.github.hexocraft.addlight.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:124) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor895.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1592]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1592]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1592]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1592]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[patched_1.12.2.jar:git-Paper-1592]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:203) ~[patched_1.12.2.jar:git-Paper-1592]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:109) ~[patched_1.12.2.jar:git-Paper-1592]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:920) ~[patched_1.12.2.jar:git-Paper-1592]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.12.2.jar:git-Paper-1592]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1592]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1592]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1592]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1592]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1592]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1592]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1592]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by TheMonDon** [comment]
I closed this thinking it was not an issue with my version but the plugin but I believe this is still a logical error, I am using [23:25:05 INFO]: This server is running Paper version git-Paper-1592 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
with FAWE: [23:25:36 INFO]: FastAsyncWorldEdit version 18.11.21-1c17b10-1231-21.5.18
[23:25:36 INFO]: Fast Async WorldEdit plugin
[23:25:36 INFO]: Author: Empire92
